name: task_manger
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^4.0.1

  flutter_switch: ^0.3.2
  shared_preferences: ^2.0.14
  flutter_bloc: ^8.0.1
  validators: ^3.0.0
  sqflite: ^2.0.2+1
  workmanager:
    git:
      url: https://github.com/sunalwaysknows/flutter_workmanager
  shared_preferences_android:
  shared_preferences_ios:
  introduction_screen: ^3.0.2

  awesome_notifications: ^0.6.21
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator: ^4.0.0

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/sounds/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 800
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-ExtraBold.ttf
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          # weight: 200
        - asset: assets/fonts/Cairo-Light.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf
